// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkAKmSD-EIGGDublm64eLhDUe6UWwKwik',
    appId: '1:76527337706:web:06efa1fa50430c84379793',
    messagingSenderId: '76527337706',
    projectId: 'kfestival-dev-team',
    authDomain: 'kfestival-dev-team.firebaseapp.com',
    storageBucket: 'kfestival-dev-team.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB1WF5pd4yGCMx85zN2i1FU_r0KikYET0',
    appId: '1:76527337706:android:a1d4f337de1f2210379793',
    messagingSenderId: '76527337706',
    projectId: 'kfestival-dev-team',
    storageBucket: 'kfestival-dev-team.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs0-kkfUfNMqNiegiA43z3hzadBY69tRU',
    appId: '1:76527337706:ios:6a3c607d29f948bd379793',
    messagingSenderId: '76527337706',
    projectId: 'kfestival-dev-team',
    storageBucket: 'kfestival-dev-team.firebasestorage.app',
    iosBundleId: 'com.example.kfestival',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs0-kkfUfNMqNiegiA43z3hzadBY69tRU',
    appId: '1:76527337706:ios:6a3c607d29f948bd379793',
    messagingSenderId: '76527337706',
    projectId: 'kfestival-dev-team',
    storageBucket: 'kfestival-dev-team.firebasestorage.app',
    iosBundleId: 'com.example.kfestival',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkAKmSD-EIGGDublm64eLhDUe6UWwKwik',
    appId: '1:76527337706:web:1b2e1bceb69aae5d379793',
    messagingSenderId: '76527337706',
    projectId: 'kfestival-dev-team',
    authDomain: 'kfestival-dev-team.firebaseapp.com',
    storageBucket: 'kfestival-dev-team.firebasestorage.app',
  );
}
